db_host: "{{ hostvars.dbserver.ansible_default_ipv4.address }}"
nginx_sites:
  default:
    - listen 80
    - server_name "_"
    - |
      location / {
        proxy_pass http://127.0.0.1:9292;
      }
