---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add mongodb repo key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.2.asc
        state: present

    - name: Add mongodb repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install MongoDB
      apt:
        update_cache: yes
        name:
          - mongodb-org
        state: present

    - name: Enable MongoDB
      systemd:
        name: mongod
        enabled: yes
        state: started
