#cloud-config

# Add user for reddit app
users:
  - name: appuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmY1Y+TWSK5hjzZpda8w34c0CXPUYK7QPSpYavE0G02YGNp8XOx9/yWaCwcpTPYhDtoyvB1St4ANd+u3Dl7vaTaItMJb0KCIv5WC3qB0Av0tC7Ejv3eEJtKh29dWTwtwH/l5dHR0Lar8hU21vX4WUF6lnSMg6YKAiq4YZXHz4+EhcG+duY+UIYRuC/6x8bI6sD18A6zwNPGkm0mK2gY6wBzqGXN+qEyOt+tFlDzld4p2QYW28vhTEdDqeo/pSBBku83Ag2+sUiyNjJ2zVccX4g/p1hzw+/dgYuNVttDqTF/BrzFxpcd9+BmZaWUHP4ccHIl5EQzbINQbmQuFlSLga9 appuser

# Update apt cache
package_update: true

# Install needed packages
packages:
  - ruby-full
  - ruby-bundler
  - build-essential
  - git

runcmd:

# Install mongo DB
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list

  - apt update
  - apt install -y mongodb-org

  - sudo systemctl start mongod
  - sudo systemctl enable mongod

# Install reddit app
  - git clone -b monolith https://github.com/express42/reddit.git
  - cd reddit
  - bundle install

  - sudo -u appuser puma -d
